sources:
  my_python_logs:
    type: file
    include:
      - "/var/logs/app.log"
    read_from: beginning

# 2. TRANSFORM: (Optional) Parse JSON
# Since my logs are JSON, Vector handles them natively, 
# but we can explicitely tell Vector to treat them as such.
# transforms:
#   parse_logs:
#     type: remap
#     inputs:
#       - my_python_logs
#     source: |
#       . = parse_json!(.message)

sinks:
  to_loki:
    type: loki
    inputs:
      - parse_logs # "parse_logs" if transforming to JSON.
    endpoint: "http://loki:3100"
    encoding:
      codec: json
    labels: # labels determine how you find logs in Grafana
      job: python-service
      env: dev